### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso#15]

**Comment by AMDphreak** [comment]
WSL is _NOT_ Windows support.
Windows support means NATIVE windows support. Sounds to me like this is still an open issue.

**Comment by AMDphreak** [comment]
Follow-up opened on the Cloud CLI repo, which still has no native Windows release/installer and still points people at WSL: https://github.com/tursodatabase/turso-cli/issues/1057 (also related: https://github.com/tursodatabase/turso-cli/issues/318). WSL is not native Windows support.
