### ISSUE TITLE
`.schema` command is broken

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso#192]
```
.Welcome to Limbo SQL shell!
> .schema
thread 'main' panicked at core/vdbe.rs:827:21:
assertion failed: *target_pc >= 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JoanFM** [comment]
I see that the `target_pc` is -2.

If we havew to check `*target_pc` shouldn't we aim to have `BranchOffset` be `u64` or `u32`?

**Comment by macroexpansion** [comment]
> I see that the `target_pc` is -2.
> 
> If we havew to check `*target_pc` shouldn't we aim to have `BranchOffset` be `u64` or `u32`?

there are some `*target_pc < 0` check too so I don't think `BranchOffset` could be an unsigned integer

**Comment by benclmnt** [comment]
I'll take a look

**Comment by pereman2** [comment]
Encoded negative BranchOffset are labels that must resolve to a correct positive value.

**Comment by JoanFM** [comment]
Wherever there is the `assert *target_pc < 0` `target_pc` is just set to another value, which seems like a weird assertion. I guess `negative` is used to determine unitialized or something
