### ISSUE TITLE
Unicode test failure on macOS

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso#243]
The test passes on Linux in the CI, but fails on my macOS at least:

```
Test FAILED: 'SELECT unicode('ð');'
returned '240'
expected '128522'
```

**Comment by jussisaurio** [comment]
Yeah noticed the same, I don't know why I ignored it, thought it was something related to my local setup or something

**Comment by benclmnt** [comment]
I tried running it interactively

```
limbo> SELECT unicode('😊');
128522
```

which is expected, but if I run `make test`, it fails

**Comment by penberg** [comment]
This is a TCL 8.5 issue, which is shipped by default on macOS. Upgrading to TCL 8.6 fixes the problem.

Anyone hitting this, just do the following:

```
brew install tcl-tk
echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
``
