### ISSUE TITLE
Move time querying and random number generation to I/O

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso#272]
We need time querying and random number generation to be deterministic for simulation. Therefore, move them to the I/O trait so that we can simulate them.

**Comment by seonWKim** [comment]
May I look into this issue?

**Comment by sonhmai** [comment]
@penberg  how does sqlite use `deterministic simulation` in testing? any references/ docs that you know of?

**Comment by barbarj** [comment]
It appears this issue is ready to be closed now, thanks to @mazchew 's work, right?
