### ISSUE TITLE
Limbo returns the rowid in place of the primary key even in cases where the primary key is not an alias for the rowid

### ISSUE THREAD

**Issue by pkolaczk** [tursodatabase/turso#438]
There are some semantic differences in how integer primary keys work in limbo vs sqlite.

Limbo (version f7e9d3a25abe1f173d04c81d4de092beacbf2927 built from main):

```
Limbo v0.0.8
Enter ".help" for usage hints.
limbo> create table foo (id int primary key, value text);
limbo> select * from foo;
limbo> insert into foo(id, value) values (1, 'foo');
limbo> insert into foo(id, value) values (1, 'bar');
limbo> select * from foo;
1|foo
2|bar
limbo> insert into foo(id, value) values (5, 'baz');
limbo> select * from foo;
1|foo
2|bar
3|baz
limbo> select id, value from foo;
1|foo
2|bar
3|baz
limbo> select rowid, value from foo;
Parse error: Column rowid not found
```

Now the same db in sqlite3:
```
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> select * from foo;
1|foo
1|bar
5|baz
sqlite> select id, value from foo;
1|foo
1|bar
5|baz
sqlite> select rowid, value from foo;
1|foo
2|bar
3|baz
```

**Comment by jussisaurio** [comment]
Thanks for the report

Alright, so your table definition says `int primary key`, not `integer primary key` -- this is actually a significant difference: the column only becomes an alias for the rowid if the declared type is exactly `integer` for the primary key, see here: https://www.sqlite.org/lang_createtable.html#rowids_and_the_integer_primary_key

This means that the table will actually have a hidden `rowid`, an `id` int column, and a `value` column. The actual issue where Limbo goes wrong is that we are improperly returning the `rowid` (which is not the same as `id`), while sqlite correctly returns `id`.

So there are at least the following issues:

1. Limbo returns the `rowid` in place of the primary key even in cases where the primary key is not an alias for the rowid:
```
limbo> create table lol (foo text primary key, value);
limbo> insert into lol (foo, value) values ('kek', 2);
limbo> select * from lol;
1|2
```

2. Limbo does not create an index on the primary key if it's not an alias for the rowid (created [issue](https://github.com/tursodatabase/limbo/issues/448))

**Comment by jussisaurio** [comment]
I went ahead and renamed the issue so I remember what this is about later

**Comment by jussisaurio** [comment]
Created https://github.com/tursodatabase/limbo/issues/448
