### ISSUE TITLE
Newline in CLI/repl causes a parse error on incomplete statement

### ISSUE THREAD

**Issue by PThorpe92** [tursodatabase/turso#450]
When entering a statement in the CLI, limbo currently makes the assumption that the user entered a complete statement, and throws a parse error when entering something like `create table users (`
![image](https://github.com/user-attachments/assets/1db5034c-0957-4574-b0de-b582d786dc08)

Expected behavior:
limbo would buffer the input and evaluate the statement when a `;` character is entered. The prompt would change to inform the user they are 'in progress' on a multi-line statement.
e.g. 

![image](https://github.com/user-attachments/assets/f4d83d15-508a-4f75-a76d-cf12b69c1dd2)
sqlite dot commands entered during multi-line statements ~~have no effect~~
EDIT: are interpreted as regular input during this time*

I have a PR ready I can submit, if this is the desired behavior.

**Comment by penberg** [comment]
@PThorpe92 Let's follow SQLite here. If you have a PR, please do submit it!
