### ISSUE TITLE
Process does not die if CLI is terminated via interrupts

### ISSUE THREAD

**Issue by alpaylan** [tursodatabase/turso#451]
The following sequence of interactions exhibit the mentioned behavior. If the user quits the CLI using the designated `.quit` CLI command, the process is gracefully shut down. If I close the CLI via `ctrl+C` or `ctrl+Z`, I get the `Locking error`. 

```
➜  limbo git:(main) target/debug/limbo localhost                                         
Limbo v0.0.8
Enter ".help" for usage hints.
limbo> .quit
Exiting Limbo SQL Shell.
➜  limbo git:(main) ✗ target/debug/limbo localhost
Limbo v0.0.8
Enter ".help" for usage hints.
limbo> 
[1]  + 76400 suspended  target/debug/limbo localhost
➜  limbo git:(main) ✗ target/debug/limbo localhost
Error: Locking error: Failed locking file. File is locked by another process
```

**Comment by krishvishal** [comment]
What OS is this? 

On WSL-2, Ubuntu 24.04 `Ctrl + C` works fine. 

`Ctrl + Z` suspends the process and the suspended process is still running and holding the lock. 

```
 ./target/release/limbo localhost
Limbo v0.0.8
Enter ".help" for usage hints.
limbo> 
Use .quit to exit or press Ctrl-C again to force quit.
limbo> 
Interrupted. Exiting...
```

**Comment by alpaylan** [comment]
Ah, it's OSX with the following parameters.

ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68

**Comment by srikarm99** [comment]
> What OS is this?
> 
> On WSL-2, Ubuntu 24.04 `Ctrl + C` works fine.
> 
> `Ctrl + Z` suspends the process and the suspended process is still running and holding the lock.
> 
> ```
>  ./target/release/limbo localhost
> Limbo v0.0.8
> Enter ".help" for usage hints.
> limbo> 
> Use .quit to exit or press Ctrl-C again to force quit.
> limbo> 
> Interrupted. Exiting...
> ```

I also face same thing, I use Ubuntu 22.04

**Comment by penberg** [comment]
Limbo uses exclusive locking by default, which means the behavior with `Ctrl-Z` is expected. That's because there is a process holding on to the file lock.

With Ctrl-C, that should obviously _not_ happen. @alpaylan are you saying you see that happening? I am also on mac and it does not reproduce:

```
% limbo foo.db
Limbo v0.0.9
Enter ".help" for usage hints.
limbo>
Use .quit to exit or press Ctrl-C again to force quit.
limbo>
Interrupted. Exiting...
% limbo foo.db
Limbo v0.0.9
Enter ".help" for usage hints.
limbo>
```

**Comment by alpaylan** [comment]
@penberg it actually does not happen with Ctrl-C, I think I was confused with it.
