### ISSUE TITLE
panicked at core\translate\emitter.rs:186:51:

### ISSUE THREAD

**Issue by serdardidan** [tursodatabase/turso#485]
Hi,

Too much panic occurs when running SQL.
An example:

limbo> create table t1 (a text);
limbo> insert into t1 values('a text for test');
limbo> insert into t1 values('a text for test2');
limbo> insert into t1 values('a text for test23');
limbo> insert into t1 values('a text for test234');
limbo> insert into t1 values('a text for test2345');
limbo> insert into t1 values('a text for test2345');
limbo> select a from t1 group by a order by a;
thread 'main' panicked at core\translate\emitter.rs:186:51:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I couldn't debug with VsCode. The error message: Cargo has produced more than one matching compilation artifact.

rustup -V
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.83.0 (90b35a623 2024-11-26)`

Os: Windows 11

**Comment by jussisaurio** [comment]
hi, thanks

should be fixed here https://github.com/tursodatabase/limbo/pull/486

**Comment by serdardidan** [comment]
Thanks for the reply.

I can debug the codes I have written. But I can't debug for Limbo. 
The error message: **Cargo has produced more than one matching compilation artifact.**

How can I debug for Limbo?
